name: Deploy

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci --include=dev
  migrate:
    runs-on: ubuntu-latest
    needs: check
    environment: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Run migrations
        run: npx prisma migrate deploy

  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    environment: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
